import { IProductDto } from "../models/iProductDto";

export const Products: IProductDto[] = [
/*  {
    productId: 1,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 2,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 3,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 4,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 5,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 6,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 7,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 8,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },
  {
    productId: 9,
    categoryId: 1,
    productCode: '',
    productName: '',
    productDesc: '',
    productPrice: 3.5,
    productQuantity: 35,
    seedQuantity: 35,
    germinationRate: 70,
    numberDays: 0,
    inStock: true,
    productImage: ''
  },*/
  {
    productId: 10,
    categoryId: 61,
    productCode: 'HM023',
    productName: "Haricot Nain Mine d'or",
    productDesc: 'Haricot nain jaune sucré et croquant, longueur de 12-15cm à maturité. <br>Les plants sont vigoureux et les fèves poussent en grappes, ce qui facilite la récolte.',
    productPrice: 3.75,
    productQuantity: 35,
    seedQuantity: 50,
    germinationRate: 90,
    numberDays: 55,
    inStock: true,
    productImage: ''
  },
  {
    productId: 11,
    categoryId: 61,
    productCode: 'HP22',
    productName: 'Haricot Nain Provider',
    productDesc: 'Plant vigoureux qui germe bien en sol plus froid.<br>Un haricot vert pâle croquant avec un vrai goût de fève, se congèle bien.<br>Productif, un standard pour une récolte abondante.',
    productPrice: 3.75,
    productQuantity: 35,
    seedQuantity: 50,
    germinationRate: 90,
    numberDays: 55,
    inStock: true,
    productImage: ''
  },
  {
    productId: 12,
    categoryId: 61,
    productCode: 'HGC22',
    productName: 'Haricot grimpant Cobra',
    productDesc: 'Haricot grimpant vert de type français. La fève est ronde, longue (18 cm) et sans filet.<br>Vignes vigoureuses et productives, notre fève préférée cuite à la vapeur, sucrée et délicieuse.<br>Produit sur une plus longue période qu’un haricot nain.',
    productPrice: 3.75,
    productQuantity: 35,
    seedQuantity: 50,
    germinationRate: 90,
    numberDays: 75,
    inStock: true,
    productImage: ''
  },
  {
    productId: 13,
    categoryId: 61,
    productCode: 'HMG23',
    productName: 'Haricot grimpant Monte Gusto',
    productDesc: 'Haricot jaune fin de type français sur un joli plant grimpant avec de petites feuilles.<br>Excellent goût.  Récolte sur une longue période.',
    productPrice: 3.75,
    productQuantity: 35,
    seedQuantity: 50,
    germinationRate: 89,
    numberDays: 75,
    inStock: true,
    productImage: ''
  },
  {
    productId: 14,
    categoryId: 61,
    productCode: 'HC24',
    productName: 'Haricot Calima',
    productDesc: "Haricot nain vert de type français, fin et long.<br>Très productif et goûteux, reste tendre même lorsque plus gros.<br>Un coup de cœur!",
    productPrice: 3.75,
    productQuantity: 0,
    seedQuantity: 60,
    germinationRate: 89,
    numberDays: 55,
    inStock: false,
    productImage: ''
  },
  {
    productId: 15,
    categoryId: 61,
    productCode: 'HRB22',
    productName: 'Haricot mauve Royal Burgundy',
    productDesc: "Haricot nain de couleur mauve très croquant avec un excellent goût de fève.  Plant vigoureux et productif qui pousse bien dans les climats plus froid.  Un classique.  La fève devient verte à la cuisson.",
    productPrice: 3.75,
    productQuantity: 35,
    seedQuantity: 60,
    germinationRate: 90,
    numberDays: 55,
    inStock: true,
    productImage: ''
  },
];